# Generated by Django 4.2.17 on 2025-02-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysPresent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_attending', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GuestConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=150)),
                ('confirmation', models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=5)),
                ('date_of_confirmation', models.DateField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('days_present', models.ManyToManyField(blank=True, to='website.dayspresent')),
            ],
        ),
    ]
