# Generated by Django 4.2.17 on 2024-12-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestconfirmation',
            name='confirmation',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não'), ('none', 'Nenhum')], max_length=5),
        ),
    ]
