# Generated by Django 4.2.17 on 2024-12-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_guestconfirmation_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestconfirmation',
            name='confirmation',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], max_length=5),
        ),
    ]
